# touch .env
# echo VUE_APP_PROD_API_KEY=${{ secrets.VUE_APP_PROD_API_KEY }} >> .env

name: deploy-to-production
run-name: 'Deploy to production'

on:
  push:
    brances:
      - main

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repo
        uses: actions/checkout@v3
      - name: checkout shared code repo
        uses: actions/checkout@v3
        with:
          repository: Ready-Set-Dice/rsd-shared.git
          ref: 'main'
          path: './src/.shared'
      - name: setup the correct version of node
        uses: actions/setup-node@v3
        with:
          node-version: '18.2'
      - name: setup the environment variables
        run: |
          touch .env
          echo VUE_APP_PROD_API_KEY=${{ secrets.VUE_APP_PROD_API_KEY }} >> .env
          echo VUE_APP_PROD_AUTH_DOMAIN=${{ secrets.VUE_APP_PROD_AUTH_DOMAIN }} >> .env
          echo VUE_APP_PROD_DATABASE_URL=${{ secrets.VUE_APP_PROD_DATABASE_URL }} >> .env
          echo VUE_APP_PROD_PROJECT_ID=${{ secrets.VUE_APP_PROD_PROJECT_ID }} >> .env
          echo VUE_APP_PROD_STORAGE_BUCKET=${{ secrets.VUE_APP_PROD_STORAGE_BUCKET }} >> .env
          echo VUE_APP_PROD_MESSAGING_SENDER_ID=${{ secrets.VUE_APP_PROD_MESSAGING_SENDER_ID }} >> .env
          echo VUE_APP_PROD_APP_ID=${{ secrets.VUE_APP_PROD_APP_ID }} >> .env
          echo VUE_APP_PROD_ANALYTICS=${{ secrets.VUE_APP_PROD_ANALYTICS }} >> .env
          echo VUE_APP_DEV_API_KEY=${{ secrets.VUE_APP_DEV_API_KEY }} >> .env
          echo VUE_APP_DEV_AUTH_DOMAIN=${{ secrets.VUE_APP_DEV_AUTH_DOMAIN }} >> .env
          echo VUE_APP_DEV_DATABASE_URL=${{ secrets.VUE_APP_DEV_DATABASE_URL }} >> .env
          echo VUE_APP_DEV_STORAGE_BUCKET=${{ secrets.VUE_APP_DEV_STORAGE_BUCKET }} >> .env
          echo VUE_APP_DEV_MESSAGING_SENDER_ID=${{ secrets.VUE_APP_DEV_MESSAGING_SENDER_ID }} >> .env
          echo VUE_APP_DEV_APP_ID=${{ secrets.VUE_APP_DEV_APP_ID }} >> .env
          echo VUE_APP_DEV_ANALYTICS=${{ secrets.VUE_APP_DEV_ANALYTICS }} >> .env
      - name: npm install, build and test
        run: |
          npm ci
          npm run build --if-present
      - name: archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-and-server
          path: |
            backend
            dist
            pc.js
            package.json
            package-lock.json